// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace PlayerScssNamespace {
  export interface IPlayerScss {
    avatar: string;
    "bank-roll": string;
    inactive: string;
    player: string;
  }
}

declare const PlayerScssModule: PlayerScssNamespace.IPlayerScss;

export = PlayerScssModule;
