// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HomeScssNamespace {
  export interface IHomeScss {
    button: string;
  }
}

declare const HomeScssModule: HomeScssNamespace.IHomeScss;

export = HomeScssModule;
