// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace GameScssNamespace {
  export interface IGameScss {
    control: string;
    footer: string;
    "game-container": string;
    "pocket-cards": string;
  }
}

declare const GameScssModule: GameScssNamespace.IGameScss;

export = GameScssModule;
