// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace CardCssNamespace {
  export interface ICardCss {
    back: string;
    card: string;
  }
}

declare const CardCssModule: CardCssNamespace.ICardCss;

export = CardCssModule;
