// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace CardScssNamespace {
  export interface ICardScss {
    back: string;
    card: string;
    hide: string;
    pocket: string;
  }
}

declare const CardScssModule: CardScssNamespace.ICardScss;

export = CardScssModule;
