// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace TableScssNamespace {
  export interface ITableScss {
    card: string;
    "community-cards": string;
    table: string;
  }
}

declare const TableScssModule: TableScssNamespace.ITableScss;

export = TableScssModule;
